name: Update some list

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: some generator
        uses: SwordfishLabs/simonecorsi-mawesome@bb3b0b0f0a78e96671d1836fc4c2c5b2f9daf523
        with:
          api-token: ${{ secrets.PERSONAL_TOKEN }}
          github-email: ${{ secrets.USER_EMAIL }}
          template-path: "template/README.ejs"
          github-name: ${{ github.repository_owner }}